import 'package:karbarab/core/helper/utils.dart';
import 'package:karbarab/features/quiz/model/quiz.dart';
import 'package:uuid/uuid.dart';
/*
=== quiz template ===
QuizModel(
  arab: '',
  voice: '',
  bahasa: '',
  date: DateTime.now(),
  cardCategory: CardCategory.Object,
  voice: '',
  cardCategory: CardCategory.Object,
  level: 1,
  id: 'nomor',
  image: '',
),

*/

List<QuizModel> getQuizData() {
  return <QuizModel>[
    QuizModel(
      arab: 'دَرَجَة',
      bahasa: 'Tangga',
      image: 'tangga.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '1',
    ),
    QuizModel(
      arab: 'بَاب',
      bahasa: 'Pintu',
      image: 'pintu.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '2',
    ),
    QuizModel(
      arab: 'كَنَّاسَة',
      bahasa: 'Sapu',
      image: 'sapu.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '3',
    ),
    QuizModel(
      arab: 'سَجَّادَة',
      bahasa: 'Karpet',
      image: 'karpet.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '4',
    ),
    QuizModel(
      arab: 'كُرْسِيّ',
      bahasa: 'Kursi',
      image: 'kursi.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '5',
    ),
    QuizModel(
      arab: 'كَنَبَة',
      bahasa: 'Sofa',
      image: 'sofa.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '6',
    ),
    QuizModel(
      arab: 'طَرَبِيْزَة',
      bahasa: 'Meja',
      image: 'meja.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '7',
    ),
    QuizModel(
      arab: 'حَقِيْبَة',
      bahasa: 'Tas',
      image: 'tas.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '8',
    ),
    QuizModel(
      arab: 'أَلْبِسَة',
      bahasa: 'Baju',
      image: 'baju.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '9',
    ),
    QuizModel(
      arab: 'بُرْنَيطَة',
      bahasa: 'Topi',
      image: 'topi.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '10',
    ),
    QuizModel(
      arab: 'تِلِفْزِيُون',
      bahasa: 'Televisi',
      image: 'televisi.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '11',
    ),
    QuizModel(
      arab: 'بَيْت',
      bahasa: 'Rumah',
      image: 'rumah.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '12',
    ),
    QuizModel(
      arab: 'نَافِذَة',
      bahasa: 'Jendela',
      image: 'jendela.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '13',
    ),
    QuizModel(
      arab: 'جَزْمَة',
      bahasa: 'Sepatu',
      image: 'sepatu.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '14',
    ),
    QuizModel(
      arab: 'شِبْشِب',
      bahasa: 'Sandal',
      image: 'sandal.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '15',
    ),
    QuizModel(
      arab: 'سَاعَة',
      bahasa: 'Jam Dinding',
      image: 'jam-dinding.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '16',
    ),
    QuizModel(
      arab: 'كَسْتَك',
      bahasa: 'Jam Tangan',
      image: 'jam-tangan.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '17',
    ),
    QuizModel(
      arab: 'وَجْه',
      bahasa: 'Wajah',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '18',
    ),
    QuizModel(
      arab: 'أنْف',
      bahasa: 'Hidung',
      image: 'hidung.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '19',
    ),
    QuizModel(
      arab: 'عَيْن',
      bahasa: 'Mata',
      image: 'mata.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '20',
    ),
    QuizModel(
      arab: 'أُذُن',
      bahasa: 'Telinga',
      image: 'telinga.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '21',
    ),
    QuizModel(
      arab: 'يَد',
      bahasa: 'Tangan',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '22',
    ),
    QuizModel(
      arab: 'صَحْفَة',
      bahasa: 'Piring',
      image: 'piring.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '23',
    ),
    QuizModel(
      arab: 'جَرْدَل',
      bahasa: 'Ember',
      image: 'ember.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '24',
    ),
    QuizModel(
      arab: 'مِظَلَّة',
      bahasa: 'Payung',
      image: 'payung.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '25',
    ),
    QuizModel(
      arab: 'طَاسِ',
      bahasa: 'Gelas',
      image: 'gelas.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '26',
    ),
    QuizModel(
      arab: 'سَيَّارَة',
      bahasa: 'Mobil',
      image: 'mobil.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '27',
    ),
    QuizModel(
      arab: 'قَاطِرَة',
      bahasa: 'Kereta Api',
      image: 'kereta-api.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '28',
    ),
    QuizModel(
      arab: 'سَفِيْنَة',
      bahasa: 'Kapal Laut',
      image: 'kapal-laut.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '29',
    ),
    QuizModel(
      arab: 'لِلطَّائِرَات',
      bahasa: 'Pesawat Terbang',
      image: 'pesawat-terbang.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '30',
    ),
    QuizModel(
      arab: 'بِسْكِلِيت',
      bahasa: 'Sepeda',
      image: 'sepeda.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '31',
    ),
    QuizModel(
      arab: 'مُوتُوسِيكل',
      bahasa: 'Sepeda Motor',
      image: 'motor.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '32',
    ),
    QuizModel(
      arab: 'أمْطَرَ',
      bahasa: 'Hujan',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '33',
    ),
    QuizModel(
      arab: 'كُرَة',
      bahasa: 'Bola',
      image: 'bola.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '34',
    ),
    QuizModel(
      arab: 'مَسْطَرَة',
      bahasa: 'Penggaris',
      image: 'penggaris.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '35',
    ),
    QuizModel(
      arab: 'عَجَلَة',
      bahasa: 'Roda',
      image: 'roda.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '36',
    ),
    QuizModel(
      arab: 'مُعَلِّم',
      bahasa: 'Guru',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '37',
    ),
    QuizModel(
      arab: 'مَدْرَسَة',
      bahasa: 'Sekolah',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '38',
    ),
    QuizModel(
      arab: 'مَكْتَب',
      bahasa: 'Kantor',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '39',
    ),
    QuizModel(
      arab: 'سُوْق',
      bahasa: 'Pasar',
      image: 'pasar.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '40',
    ),
    QuizModel(
      arab: 'كِتَاب',
      bahasa: 'Buku',
      image: 'buku.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '41',
    ),
    QuizModel(
      arab: 'قِنِّيْنَة',
      bahasa: 'Botol',
      image: 'botol.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '42',
    ),
    QuizModel(
      arab: 'خِزَانَة',
      bahasa: 'Lemari',
      image: 'lemari.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '43',
    ),
    QuizModel(
      arab: 'فِرَاش',
      bahasa: 'Kasur',
      image: 'kasur.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '44',
    ),
    QuizModel(
      arab: 'مِفْتَاح',
      bahasa: 'Kunci',
      image: 'kunci.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '45',
    ),
    QuizModel(
      arab: 'لَمْبَة',
      bahasa: 'Lampu',
      image: 'lampu.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '46',
    ),
    QuizModel(
      arab: 'دَجَاجَة',
      bahasa: 'Ayam',
      image: 'ayam.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '47',
    ),
    QuizModel(
      arab: 'بَعِيْر',
      bahasa: 'Unta',
      image: 'unta.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '48',
    ),
    QuizModel(
      arab: 'حِصَان',
      bahasa: 'Kuda',
      image: 'kuda.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '49',
    ),
    QuizModel(
      arab: 'نَظَّارَات',
      bahasa: 'Kacamata',
      image: 'kacamata.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '50',
    ),
    QuizModel(
      arab: 'بُرْتُقَال',
      bahasa: 'Buah Jeruk',
      image: 'buah-jeruk.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '51',
    ),
    QuizModel(
      arab: 'تُفَّاحَة',
      bahasa: 'Buah Apel',
      image: 'buah-apel.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '52',
    ),
    QuizModel(
      arab: 'عِنَب',
      bahasa: 'Buah Anggur',
      image: 'buah-anggur.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '53',
    ),
    QuizModel(
      arab: 'مَانْجَا',
      image: 'buah-mangga.jpg',
      bahasa: 'Buah Mangga',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '54',
    ),
    QuizModel(
      arab: 'بَطَّة',
      bahasa: 'Bebek',
      image: 'bebek.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '55',
    ),
    QuizModel(
      arab: 'وَزَّة',
      bahasa: 'Angsa',
      image: 'angsa.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '56',
    ),
    QuizModel(
      arab: 'أرْنَب',
      bahasa: 'Kelinci',
      image: 'kelinci.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '57',
    ),
    QuizModel(
      arab: 'مِعْز',
      bahasa: 'Kambing',
      image: 'kambing.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '58',
    ),
    QuizModel(
      arab: 'بَقَرَة',
      bahasa: 'Sapi',
      image: 'sapi.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '59',
    ),
    QuizModel(
      arab: 'جَامُوْس',
      bahasa: 'Kerbau',
      image: 'kerbau.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '60',
    ),
    QuizModel(
      arab: 'مَوْز',
      bahasa: 'Buah Pisang',
      image: 'buah-pisang.jpg',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '61',
    ),
    QuizModel(
      arab: 'مَاء',
      bahasa: 'Air',
      date: DateTime.now(),
      cardCategory: CardCategory.Object,
      voice: '',
      level: 1,
      id: '62',
    ),
  ];
}
